driver:
  name: vagrant

platforms:
  - name: centos-6

provisioner:
  name: salt_solo
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  salt_install: bootstrap
  salt_env: main
  is_file_root: True
  state_top_from_file: True
  pillars-from-files:
    users.sls: test_pillars/users.sls
  pillars:
    top.sls:
      main:
        '*':
          - users

suites:
  - name: default